name: auto-make

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64
    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/cmake/Switch.cmake

      - name: Clean build
        run: make clean || true

      - name: Build
        run: make

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deploy-files
          path: deploy/
